### ISSUE TITLE
Integer enum with value description

### ISSUE THREAD

**Issue by sbahloul** [javalin/javalin-openapi#226]
First of all, thank you for the great work.

Quick question: which annotations should be used to specify an integer enum with values description ?

```yaml
components:
  schemas:
    RequestTypeEnum:
      type: integer
      enum:
        - 1
        - 2
      description: >
        Sort order:
          * `1` - Description of the requestType = 1
          * `2` - Description of the requestType = 2
```

Thank you,
Sebastien
