### ISSUE TITLE
unwanted "is" prefix removal

### ISSUE THREAD

**Issue by f1qwase** [javalin/javalin-openapi#89]
Hi @dzikoysk and first of all many thanks for your work

I have a model in api with a boolean parameter prefixed with "is", saying
```kotlin
data class User(
  val name: String,
  val is_verified: Boolean,
)
```

but this prefix is removed in OpenApi spec so I got
```yaml
User:
  type: object
  additionalProperties: false
  properties:
    name:
      type: string
    _verified:
      type: boolean
  required:
  - name
  - _verified
```

As far as I understand this is behaviour by design but as you can see it is inconvinient in my case
Is there a way to keep this without removing all `is_*` paramaters from my API?
