### ISSUE TITLE
Enum class as reference

### ISSUE THREAD

**Issue by f1qwase** [javalin/javalin-openapi#97]
now `enum classes` are inlined in classes that use them which leads to genereting excessive classes from OpenAPI spec in case of different models use the same `enum`
lets look on the following code

```kotlin
enum class Sign {
    POSITIVE,
    NEGATIVE,
    ZERO;
}

data class A(
    val sign: Sign,
)

data class B(
    val sign: Sign,
)

data class C(
    val sign: Sign,
)

data class XXX(
    val a: A,
    val b: B,
    val c: C,
)
```

is transformed into 
```yaml
XXX:
  type: object
  additionalProperties: false
  properties:
    a:
      "$ref": "#/components/schemas/A"
    b:
      "$ref": "#/components/schemas/B"
    c:
      "$ref": "#/components/schemas/C"
  required:
  - a
  - b
  - c
A:
  type: object
  properties:
    sign:
      type: string
      enum:
      - POSITIVE
      - NEGATIVE
      - ZERO
  required:
  - sign
B:
  type: object
  properties:
    sign:
      type: string
      enum:
      - POSITIVE
      - NEGATIVE
      - ZERO
  required:
  - sign
C:
  type: object
  properties:
    sign:
      type: string
      enum:
      - POSITIVE
      - NEGATIVE
      - ZERO
  required:
  - sign
```
is it possible not to inline and keep `enum class` as it happened with 'normal' classes (`A`, `B`, `C`):
```yaml
XXX:
  type: object
  properties:
    a:
      "$ref": "#/components/schemas/A"
    b:
      "$ref": "#/components/schemas/B"
    c:
      "$ref": "#/components/schemas/C"
  required:
  - a
  - b
  - c
A:
  type: object
  properties:
    sign:
      "$ref": "#/components/schemas/Sign"
  required:
  - sign
B:
  type: object
  properties:
    sign:
       "$ref": "#/components/schemas/Sign"
  required:
  - sign
C:
  type: object
  properties:
    sign:
      "$ref": "#/components/schemas/Sign"
  required:
  - sign
Sign:
  type: string
  enum:
  - POSITIVE
  - NEGATIVE
  - ZERO
```
